### ISSUE TITLE
shortchanged by acf2betascan

### ISSUE THREAD

**Issue by jh041** [grenaud/glactools#10]
Hi Grenaud,

I've never had any problem with the glactools acf2betascan conversion before, until today when it is outputting fewer loci than are input.

_**glactools acf2betascan --fold qt6.acf > qt6.beta.txt
Program ACF2BETASCAN  looked at  9005 records, terminated gracefully**_

9005 is the correct number of SNP loci. But... 

**_wc qt6.beta.txt
8961  26883 106058 qt6.beta.txt_**

Can you help me find where my missing 44 loci went and how to get them back?

**Comment by grenaud** [comment]
Dear John,
I am super swamped for the rest of the week, do you mind if I address this
early next week?

Sorry again!

Gabriel

**Comment by jh041** [comment]
Standing by until next week.

**Comment by grenaud** [comment]
Dear John, my apologies for the delay, I see in the code that it will skip sites where the alternative is not resolved (essentially non segregading site), could you do a "glactools view qt6.acf | grep N"? otherwise, could you send me the acf file via email or send a link to a dropbox?

**Comment by jh041** [comment]
Ah, that makes perfect sense. I recently removed some samples from this data, so the 44 loci must have only been polymorphic for that group. 

**glactools view qt6.acf | grep 'N' | wc
     44   16016   96091**

I didn't realize that the program would remove such loci, but that is exactly what happened. Thanks for the insight.
