### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by DcornishUCL** [grenaud/glactools#27]
Hi, 

I am attempting to compile your package from github however, I am receiving the following error messages (below). Do you know the meaning of these or how to rectify the problem? Any help would be much appreciated. 

Thank you and best wishes,

Dean 

.../glactools/tabixpp/htslib/cram/cram_codecs.c:1768: undefined reference to `__intel_sse2_strlen'
htslib/libhts.a(cram_codecs.o): In function `cram_byte_array_stop_decode_block':
.../glactools/tabixpp/htslib/cram/cram_codecs.c:1682: undefined reference to `_intel_fast_memcpy'
collect2: error: ld returned 1 exit status
make[2]: *** [tabix++] Error 1
make[2]: Leaving directory `.../glactools/tabixpp'
make[1]: *** [all-recur] Error 1
make[1]: Leaving directory `.../glactools/tabixpp'
make: *** [tabixpp/tabix.o] Error 2

**Comment by grenaud** [comment]
Just a question can you compile tabixpp?

tir. d. 15. feb. 2022 3.13 PM skrev Dean Cornish ***@***.***>:

**Comment by DcornishUCL** [comment]
Hi, 

I just tried to compile tabixpp but that also produces an error: 

git clone https://github.com/ekg/tabixpp 

cd tabixpp 

make 

*** No rule to make target `htslib/htslib/bgzf.h', needed by `tabix.o'.  Stop.

Best,

Dean

**Comment by grenaud** [comment]
ok can you build htslib?

**Comment by DcornishUCL** [comment]
Hi, 

I built htslib and attempted to make glactools again and this successfully completed. Thanks so much for your help. 

Dean
