### ISSUE TITLE
--onlyGT confusion

### ISSUE THREAD

**Issue by DcornishUCL** [grenaud/glactools#28]
Hi, 

I am converting a multi-sample VCF file to glactools acf format and I am using the --onlyGT flag since my VCF contains only genotypes. Weirdly, when I remove this flag, glactools still runs and outputs a file even though I have checked and confirmed there are no PL fields in my VCF...

`grep "##FORMAT=" ALLchr_CEUlist_concat.vcf`
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype"> 

Does glactools interpret that a VCF contains only genotypes without the need for --onlyGT or am I misunderstanding the flag? Based on the comment in Vcf2ACF.cpp I assumed that glactools uses the PL field which is not present in my VCF. 

Best,

Dean

**Comment by grenaud** [comment]
you do not use --onlyGT, it will use the PL fields, if they are missing, it will treat the site/sample as missing data.

Also, I encourage you to post on biostars and email me, others might have this question. Also, this does not seem like a bug :-)
