### ISSUE TITLE
Error in vcfm2acf

### ISSUE THREAD

**Issue by LiShuhang-gif** [grenaud/glactools#29]
Hi, I am currently trying to convert a VCF file to an ACF file using glactools. However, I have encountered the following error message:

```
Error, missing data in the EPO file
Error: GlacParser tried to read 4 bytes but got 0
```

I tried the solution in another issue. I've rewritten "chr22" as "22". However, this allowed some chromosomes to run smoothly, while others still reported errors. 

```
Error, missing data in the EPO file
Warning: No EOF marker, likely due to an I/O error
Error: GlacParser tried to read 2 bytes but got 0
```

I wonder if you have any suggestions for this? By the way, my variants were mapped to hg38 rather than hg19/37. Could this be the cause of the error message? Looking forward to your reply, thank you!

**Comment by grenaud** [comment]
Hello! Yes the EPO was computed on hg19 not 38. I will write on my to-do list to try to find an EPO alignment that for hg38. Thank you for bringing this my attention.

**Comment by LiShuhang-gif** [comment]
Thank you for your reply! I am looking forward to your newly generated EPO file on hg38. By the way, I would like to ask how to obtain the required outgroup EPO file? Is it calculated by any software? Or which website can I download it from? Thanks!

**Comment by LiShuhang-gif** [comment]
Thanks again! I want to make sure whether the EPO files of chimpanzee downloaded from this website can directly be used in glactools? Or should I parse the EPO file of chimpanzee which I download from this ensembl website using epoParser first?

**Comment by grenaud** [comment]
Not directly, you need to run it through epoParser which will produce a tab-delimited file.

**Comment by LiShuhang-gif** [comment]
Hi, I'm really sorry for the late reply due to my busy assessment.  By the way, I was wondering if you generated an EPO file for hG38?  Thanks!

**Comment by grenaud** [comment]
Hey! I manage to find the EPO files on the ensemble FTP, I am parsing it now. Buzz me again next week.

**Comment by LiShuhang-gif** [comment]
Hey! I wonder if you have already found the EPO files on the ensemble FTP and generated an EPO file for hG38? Thanks in advance!
