### ISSUE TITLE
Options not working in glf2acf

### ISSUE THREAD

**Issue by nwales** [grenaud/glactools#3]
Hi Gabriel,

I'm wanted to test out some different PL options in the glf2acf conversion, but I am getting an error.  

The default option works great, with a command like this:
`glactools glf2acf file.glf.gz > file.default_PL.acf.gz`

But when I add a PL option to the same command: 
`glactools glf2acf --minPL 30 file.glf.gz > file.30_PL.acf.gz`

I get this error message:
`The last argument is the  <glf file>`

I also tried the -u option for uncompressed output and it gives the same error message. Could you please let me know if options should be entered differently or if there is a bug to fix?

Thanks! 
Nathan

**Comment by grenaud** [comment]
Hey Nathan, I just fixed it. Thanks for reporting this! Do a 
`git status
 git pull origin master
 make`

and try again. Let me know if this works and I will close the issue.

**Comment by nwales** [comment]
It's perfect. Thanks for the quick fix!
