### ISSUE TITLE
Problems with make glactools

### ISSUE THREAD

**Issue by RSchley** [grenaud/glactools#33]
Hi there

I am having major problems with installing glactools. Despite installing the correct libraries (as far as I am aware), when I run `make`, it gives this error:

```
/usr/bin/ld: cannot find -lcurl
collect2: error: ld returned 1 exit status
make: *** [Makefile:66: glactools] Error 1
```

Thinking it may have been a peculiarity of our computing cluster, I tried to install it locally on my linux subsystem. But, when it finishes 'make', the executable for glactools does not exist. There are some allusions to problems with htslib while making, but `make` seems to finish normally.

I was wondering - is there any chance of a conda package for glactools to simplify installation, e.g. on computing clusters?

Thanks so much
Rowan

**Comment by grenaud** [comment]
Hi Rowan,
Is there a static binary in the releases?

Gabriel

**Comment by RSchley** [comment]
Hi Gabriel

Apologies, I am not sure what you mean. Is there a static binary on which releases? The conda libraries I installed before running `make` on glactools?

Sorry for the confusion, and thank you for the response.
Rowan

**Comment by RSchley** [comment]
Ah - just found the static binary for glactools [here](https://github.com/grenaud/glactools/releases/tag/v1.0.9) - it is working beautifully! Thank you.
