### ISSUE TITLE
curl error during make: install failure

### ISSUE THREAD

**Issue by pbpearman** [grenaud/glactools#7]
I am on Ubuntu 16.04.  Late in make, I get the following errors:

/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:171: undefined reference to `curl_easy_getinfo'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:185: undefined reference to `curl_easy_getinfo'
htslib/libhts.a(hfile_libcurl.o): In function `wait_perform':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:693: undefined reference to `curl_multi_fdset'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:714: undefined reference to `curl_multi_perform'
htslib/libhts.a(hfile_libcurl.o): In function `process_messages':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:669: undefined reference to `curl_multi_info_read'
htslib/libhts.a(hfile_libcurl.o): In function `wait_perform':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:696: undefined reference to `curl_multi_timeout'
htslib/libhts.a(hfile_libcurl.o): In function `libcurl_close':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1073: undefined reference to `curl_easy_pause'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1082: undefined reference to `curl_multi_remove_handle'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1086: undefined reference to `curl_easy_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1087: undefined reference to `curl_multi_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1082: undefined reference to `curl_multi_remove_handle'
htslib/libhts.a(hfile_libcurl.o): In function `libcurl_write':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:845: undefined reference to `curl_easy_pause'
htslib/libhts.a(hfile_libcurl.o): In function `libcurl_exit':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:274: undefined reference to `curl_share_cleanup'
htslib/libhts.a(hfile_libcurl.o): In function `restart_from_position':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:950: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:969: undefined reference to `curl_easy_duphandle'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:973: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:974: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:975: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1052: undefined reference to `curl_easy_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:985: undefined reference to `curl_multi_add_handle'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1052: undefined reference to `curl_easy_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1052: undefined reference to `curl_easy_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:992: undefined reference to `curl_easy_pause'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1012: undefined reference to `curl_multi_remove_handle'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1015: undefined reference to `curl_easy_reset'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1016: undefined reference to `curl_multi_remove_handle'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1044: undefined reference to `curl_easy_reset'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1045: undefined reference to `curl_multi_remove_handle'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1025: undefined reference to `curl_easy_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1027: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1028: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1018: undefined reference to `curl_easy_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1031: undefined reference to `curl_easy_reset'
htslib/libhts.a(hfile_libcurl.o): In function `libcurl_open':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1148: undefined reference to `curl_multi_init'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1151: undefined reference to `curl_easy_init'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1155: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1159: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1167: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1168: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1169: undefined reference to `curl_easy_setopt'
htslib/libhts.a(hfile_libcurl.o):/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1176: more undefined references to `curl_easy_setopt' follow
htslib/libhts.a(hfile_libcurl.o): In function `libcurl_open':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1207: undefined reference to `curl_multi_add_handle'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1215: undefined reference to `curl_easy_getinfo'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1235: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1236: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1237: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1248: undefined reference to `curl_easy_getinfo'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1258: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1259: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1286: undefined reference to `curl_easy_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1287: undefined reference to `curl_multi_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1279: undefined reference to `curl_multi_remove_handle'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1162: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1163: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1202: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1194: undefined reference to `curl_easy_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1269: undefined reference to `curl_easy_getinfo'
htslib/libhts.a(hfile_libcurl.o): In function `libcurl_read':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:786: undefined reference to `curl_easy_pause'
htslib/libhts.a(hfile_libcurl.o): In function `hfile_plugin_init_libcurl':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1447: undefined reference to `curl_global_init'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1450: undefined reference to `curl_share_init'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1452: undefined reference to `curl_share_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1453: undefined reference to `curl_share_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1454: undefined reference to `curl_share_setopt'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1480: undefined reference to `curl_version_info'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1456: undefined reference to `curl_share_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1457: undefined reference to `curl_global_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1469: undefined reference to `curl_share_cleanup'
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:1470: undefined reference to `curl_global_cleanup'
htslib/libhts.a(hfile_libcurl.o): In function `libcurl_exit':
/home/bgppermp/Downloads/glactools/htslib/hfile_libcurl.c:296: undefined reference to `curl_global_cleanup'
collect2: error: ld returned 1 exit status
Makefile:54: recipe for target 'glactools' failed
make: *** [glactools] Error 1
glactools$ 

And I have:
glactools$ curl --version
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

Have I missed something?

**Comment by grenaud** [comment]
just so I can diagnose a bit better, could you go in the glactools directory, then do:
```
cd htslib
make clean
make
```

**Comment by pbpearman** [comment]
Here is what I got:

glactools$ cd htslib
htslib$ make clean
rm -f test/*.tmp test/*.tmp.* test/tabix/*.tmp.* test/tabix/FAIL*
rm -f *.o *.pico cram/*.o cram/*.pico test/*.o test/*.dSYM version.h
rm -f libhts.so libhts.so.*
rm -f libhts.a bgzip htsfile tabix  test/hts_endian test/fieldarith test/hfile test/pileup test/sam test/test_bgzf test/test_kstring test/test_realn test/test-regidx test/test_view test/test_index test/test-vcf-api test/test-vcf-sweep test/test-bcf-sr test/fuzz/hts_open_fuzzer.o test/test-bcf-translate test/test-parse-reg test/thrash_threads1 test/thrash_threads2 test/thrash_threads3 test/thrash_threads4 test/thrash_threads5 test/thrash_threads6 test/thrash_threads7
htslib$ make
gcc -g -Wall -O2 -I.  -c -o kfunc.o kfunc.c
gcc -g -Wall -O2 -I.  -c -o knetfile.o knetfile.c
gcc -g -Wall -O2 -I.  -c -o kstring.o kstring.c
gcc -g -Wall -O2 -I.  -c -o bcf_sr_sort.o bcf_sr_sort.c
gcc -g -Wall -O2 -I.  -c -o bgzf.o bgzf.c
gcc -g -Wall -O2 -I.  -c -o errmod.o errmod.c
gcc -g -Wall -O2 -I.  -c -o faidx.o faidx.c
gcc -g -Wall -O2 -I.  -c -o header.o header.c
gcc -g -Wall -O2 -I.  -c -o hfile.o hfile.c
gcc -g -Wall -O2 -I.  -c -o hfile_net.o hfile_net.c
echo '#define HTS_VERSION "1.9-288-g830c061"' > version.h
gcc -g -Wall -O2 -I.  -c -o hts.o hts.c
gcc -g -Wall -O2 -I.  -c -o hts_os.o hts_os.c
gcc -g -Wall -O2 -I.  -c -o md5.o md5.c
gcc -g -Wall -O2 -I.  -c -o multipart.o multipart.c
gcc -g -Wall -O2 -I.  -c -o probaln.o probaln.c
gcc -g -Wall -O2 -I.  -c -o realn.o realn.c
gcc -g -Wall -O2 -I.  -c -o regidx.o regidx.c
gcc -g -Wall -O2 -I.  -c -o region.o region.c
gcc -g -Wall -O2 -I.  -c -o sam.o sam.c
gcc -g -Wall -O2 -I.  -c -o synced_bcf_reader.o synced_bcf_reader.c
gcc -g -Wall -O2 -I.  -c -o vcf_sweep.o vcf_sweep.c
gcc -g -Wall -O2 -I.  -c -o tbx.o tbx.c
gcc -g -Wall -O2 -I.  -c -o textutils.o textutils.c
gcc -g -Wall -O2 -I.  -c -o thread_pool.o thread_pool.c
gcc -g -Wall -O2 -I.  -c -o vcf.o vcf.c
gcc -g -Wall -O2 -I.  -c -o vcfutils.o vcfutils.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_codecs.o cram/cram_codecs.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_decode.o cram/cram_decode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_encode.o cram/cram_encode.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_external.o cram/cram_external.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_index.o cram/cram_index.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_io.o cram/cram_io.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_samtools.o cram/cram_samtools.c
gcc -g -Wall -O2 -I.  -c -o cram/cram_stats.o cram/cram_stats.c
gcc -g -Wall -O2 -I.  -c -o cram/mFILE.o cram/mFILE.c
gcc -g -Wall -O2 -I.  -c -o cram/open_trace_file.o cram/open_trace_file.c
gcc -g -Wall -O2 -I.  -c -o cram/pooled_alloc.o cram/pooled_alloc.c
gcc -g -Wall -O2 -I.  -c -o cram/rANS_static.o cram/rANS_static.c
gcc -g -Wall -O2 -I.  -c -o cram/string_alloc.o cram/string_alloc.c
gcc -g -Wall -O2 -I.  -c -o hfile_libcurl.o hfile_libcurl.c
ar -rc libhts.a kfunc.o knetfile.o kstring.o bcf_sr_sort.o bgzf.o errmod.o faidx.o header.o hfile.o hfile_net.o hts.o hts_os.o md5.o multipart.o probaln.o realn.o regidx.o region.o sam.o synced_bcf_reader.o vcf_sweep.o tbx.o textutils.o thread_pool.o vcf.o vcfutils.o cram/cram_codecs.o cram/cram_decode.o cram/cram_encode.o cram/cram_external.o cram/cram_index.o cram/cram_io.o cram/cram_samtools.o cram/cram_stats.o cram/mFILE.o cram/open_trace_file.o cram/pooled_alloc.o cram/rANS_static.o cram/string_alloc.o hfile_libcurl.o
ranlib libhts.a
gcc -g -Wall -O2 -I.  -fpic -c -o kfunc.pico kfunc.c
gcc -g -Wall -O2 -I.  -fpic -c -o knetfile.pico knetfile.c
gcc -g -Wall -O2 -I.  -fpic -c -o kstring.pico kstring.c
gcc -g -Wall -O2 -I.  -fpic -c -o bcf_sr_sort.pico bcf_sr_sort.c
gcc -g -Wall -O2 -I.  -fpic -c -o bgzf.pico bgzf.c
gcc -g -Wall -O2 -I.  -fpic -c -o errmod.pico errmod.c
gcc -g -Wall -O2 -I.  -fpic -c -o faidx.pico faidx.c
gcc -g -Wall -O2 -I.  -fpic -c -o header.pico header.c
gcc -g -Wall -O2 -I.  -fpic -c -o hfile.pico hfile.c
gcc -g -Wall -O2 -I.  -fpic -c -o hfile_net.pico hfile_net.c
gcc -g -Wall -O2 -I.  -fpic -c -o hts.pico hts.c
gcc -g -Wall -O2 -I.  -fpic -c -o hts_os.pico hts_os.c
gcc -g -Wall -O2 -I.  -fpic -c -o md5.pico md5.c
gcc -g -Wall -O2 -I.  -fpic -c -o multipart.pico multipart.c
gcc -g -Wall -O2 -I.  -fpic -c -o probaln.pico probaln.c
gcc -g -Wall -O2 -I.  -fpic -c -o realn.pico realn.c
gcc -g -Wall -O2 -I.  -fpic -c -o regidx.pico regidx.c
gcc -g -Wall -O2 -I.  -fpic -c -o region.pico region.c
gcc -g -Wall -O2 -I.  -fpic -c -o sam.pico sam.c
gcc -g -Wall -O2 -I.  -fpic -c -o synced_bcf_reader.pico synced_bcf_reader.c
gcc -g -Wall -O2 -I.  -fpic -c -o vcf_sweep.pico vcf_sweep.c
gcc -g -Wall -O2 -I.  -fpic -c -o tbx.pico tbx.c
gcc -g -Wall -O2 -I.  -fpic -c -o textutils.pico textutils.c
gcc -g -Wall -O2 -I.  -fpic -c -o thread_pool.pico thread_pool.c
gcc -g -Wall -O2 -I.  -fpic -c -o vcf.pico vcf.c
gcc -g -Wall -O2 -I.  -fpic -c -o vcfutils.pico vcfutils.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_codecs.pico cram/cram_codecs.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_decode.pico cram/cram_decode.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_encode.pico cram/cram_encode.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_external.pico cram/cram_external.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_index.pico cram/cram_index.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_io.pico cram/cram_io.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_samtools.pico cram/cram_samtools.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/cram_stats.pico cram/cram_stats.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/mFILE.pico cram/mFILE.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/open_trace_file.pico cram/open_trace_file.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/pooled_alloc.pico cram/pooled_alloc.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/rANS_static.pico cram/rANS_static.c
gcc -g -Wall -O2 -I.  -fpic -c -o cram/string_alloc.pico cram/string_alloc.c
gcc -g -Wall -O2 -I.  -fpic -c -o hfile_libcurl.pico hfile_libcurl.c
gcc -shared -Wl,-soname,libhts.so.2to3part10  -o libhts.so kfunc.pico knetfile.pico kstring.pico bcf_sr_sort.pico bgzf.pico errmod.pico faidx.pico header.pico hfile.pico hfile_net.pico hts.pico hts_os.pico md5.pico multipart.pico probaln.pico realn.pico regidx.pico region.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico textutils.pico thread_pool.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/string_alloc.pico hfile_libcurl.pico -lz -lm -lbz2 -llzma -lcurl -lpthread
ln -sf libhts.so libhts.so.2to3part10
gcc -g -Wall -O2 -I.  -c -o bgzip.o bgzip.c
gcc  -o bgzip bgzip.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o htsfile.o htsfile.c
gcc  -o htsfile htsfile.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o tabix.o tabix.c
gcc  -o tabix tabix.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/hts_endian.o test/hts_endian.c
gcc  -o test/hts_endian test/hts_endian.o -lz -lm -lbz2 -llzma -lcurl
gcc -g -Wall -O2 -I.  -c -o test/fieldarith.o test/fieldarith.c
gcc  -o test/fieldarith test/fieldarith.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/hfile.o test/hfile.c
gcc  -o test/hfile test/hfile.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/pileup.o test/pileup.c
gcc  -o test/pileup test/pileup.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/sam.o test/sam.c
gcc  -o test/sam test/sam.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test_bgzf.o test/test_bgzf.c
gcc  -o test/test_bgzf test/test_bgzf.o libhts.a -lz -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test_kstring.o test/test_kstring.c
gcc  -o test/test_kstring test/test_kstring.o libhts.a -lz -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test_realn.o test/test_realn.c
gcc  -o test/test_realn test/test_realn.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test-regidx.o test/test-regidx.c
gcc  -o test/test-regidx test/test-regidx.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test_view.o test/test_view.c
gcc  -o test/test_view test/test_view.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test_index.o test/test_index.c
gcc  -o test/test_index test/test_index.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test-vcf-api.o test/test-vcf-api.c
gcc  -o test/test-vcf-api test/test-vcf-api.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test-vcf-sweep.o test/test-vcf-sweep.c
gcc  -o test/test-vcf-sweep test/test-vcf-sweep.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test-bcf-sr.o test/test-bcf-sr.c
gcc  -o test/test-bcf-sr test/test-bcf-sr.o libhts.a -lz -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/fuzz/hts_open_fuzzer.o test/fuzz/hts_open_fuzzer.c
gcc -g -Wall -O2 -I.  -c -o test/test-bcf-translate.o test/test-bcf-translate.c
gcc  -o test/test-bcf-translate test/test-bcf-translate.o libhts.a -lz -lz -lm -lbz2 -llzma -lcurl -lpthread
gcc -g -Wall -O2 -I.  -c -o test/test-parse-reg.o test/test-parse-reg.c
gcc  -o test/test-parse-reg test/test-parse-reg.o libhts.a -lz -lm -lbz2 -llzma -lcurl -lpthread
htslib$

**Comment by grenaud** [comment]
so htslib has built successfully?

**Comment by pbpearman** [comment]
Well, no errors were produced...

**Comment by grenaud** [comment]
it seems to have worked, from there, can you do a 
`cd .. 
`
and 

`make`
and post the output.

**Comment by pbpearman** [comment]
You wrote email to say you updated the makefile.  I re-cloned the repo and then compiled.  It finished without errors :-)  I will test this as soon as I get the chance.  Thanks for addressing this issue.
Cheers,
Peter
